def Perguntas():
  return ["What idea, product or service do you have in mind?",
           "How many benefits of your idea can you list?",
           "Why does your audience need this product?",
           "How will people use this product or service?",
           "How do you plan to monetize this MVP?",
           "Why will the public choose your solution and not other competitors that are already on the market?",
           "Who is your target audience?",
           "Have you already carried out any market research to validate your demand?",
           "What metrics do you have in mind to quantify the success of your MVP? (Number of customers, revenue, number of views, number of good reviews.....)",
          "Processamento inicial inicial",
          "Pergunta inicial gerada 1",
          "Pergunta inicial gerada 2",
          "Pergunta inicial gerada 3",
          "Pergunta inicial gerada 4",
          "Pergunta inicial gerada 5",
          "Pergunta inicial gerada 6",
          "Pergunta inicial gerada 7",
          "Pergunta inicial gerada 8",
          "Pergunta inicial gerada 9",
          "Pergunta inicial gerada 10",
          "Processamento inicial",
          "Criação do PDF inicial",
          "Criação do Subgrafo inicial",
          "Envio do arquivo inicial",
          "What is the problem you believe our MVP is solving?",
          "Do you find the provided solution relevant and urgent for the defined problem? Why?",
          "How do you think our solution addresses the problem identified?",
          "How significant do you think this problem is in the current market?\n- Please rate the market need from 1 (low urgency) to 10 (high urgency).",
          "What aspects of your solution do you find unique compared to existing market alternatives?",
          "In your opinion, why is our solution superior to other available options in the market?",
          "How does our MVP add value to customers?",
          "Processamento Picth Aprofundadas",
          "Pergunta Picth gerada 1",
          "Pergunta Picth gerada 2",
          "Pergunta Picth gerada 3",
          "Pergunta Picth gerada 4",
          "Pergunta Picth gerada 5",
          "Pergunta Picth gerada 6",
          "Pergunta Picth gerada 7",
          "Pergunta Picth gerada 8",
          "Pergunta Picth gerada 9",
          "Pergunta Picth gerada 10",
          "Processamento Picth",
          "Criação do PDF Picth",
          "Criação do Subgrafo Picth",
          "Envio do arquivo Picth",
          "What are the general objectives of your marketing strategy for the MVP?",
          "Can you list the specific KPIs (Key Performance Indicators) you plan to use to measure the success of our marketing strategy?",
          "Can you describe the market segments we are targeting?",
          "Are there plans to expand the target audience in the future? If so, how?",
          "Have specific customer personas been developed? If so, please describe one of them.",
          "What marketing channels do you recommend for our MVP and why? Options might include digital (email, PPC), social media (Facebook, Instagram, LinkedIn), traditional (TV, print, radio), etc.",
          "How have you defined the visual identity and branding for the MVP?",
          "How flexible is the implementation schedule to accommodate potential adjustments based on market response?",
          "Processamento Marketing Aprofundadas",
          "Pergunta Marketing gerada 1",
          "Pergunta Marketing gerada 2",
          "Pergunta Marketing gerada 3",
          "Pergunta Marketing gerada 4",
          "Pergunta Marketing gerada 5",
          "Pergunta Marketing gerada 6",
          "Pergunta Marketing gerada 7",
          "Pergunta Marketing gerada 8",
          "Pergunta Marketing gerada 9",
          "Pergunta Marketing gerada 10",
          "Processamento Marketing",
          "Criação do PDF Marketing",
          "Criação do Subgrafo Marketing",
          "Envio do arquivo Marketing",
          "Processamento Personas",
          "Criação do PDF Personas",
          "Criação do Subgrafo Personas",
          "Envio do arquivo Personas",
          "Who would most benefit from this product or service?",
           "Describe two other benefits that this MVP has that were not observed?",
           "In your opinion, who would be the best target audience and why?"
           "What is your recommendation for the value of this mvp for the end customer? Justify your answer.",
           "What is the size of the market that will buy this product or service?"
           "Who would be the competitors for this product or service?"
           "Do you consider this product or service viable?",
           "What are the most efficient channels to reach our target audience?",
           "If you could improve this MVP proposal, what would you improve?",
          "Processamento intermediario Aprofundadas",
          "Pergunta Aprofundadas gerada 1",
          "Pergunta Aprofundadas gerada 2",
          "Pergunta Aprofundadas gerada 3",
          "Pergunta Aprofundadas gerada 4",
          "Pergunta Aprofundadas gerada 5",
          "Pergunta Aprofundadas gerada 6",
          "Pergunta Aprofundadas gerada 7",
          "Pergunta Aprofundadas gerada 8",
          "Pergunta Aprofundadas gerada 9",
          "Pergunta Aprofundadas gerada 10",
          "Processamento Aprofundadas",
          "Criação do PDF Aprofundadas",
          "Criação do Subgrafo Aprofundadas",
          "Envio do arquivo Aprofundadas",
          """What are the primary functions and features that must be included in the MVP to deliver value to early customers?
   - Feature 1:
   - Feature 2:
   - Feature 3:""",
          "Are there any specific design requirements or user interface elements that are essential for the MVP?",
          """What is the projected timeline for each development phase of the MVP? Please provide a detailed breakdown of the timeline (e.g., Research, Design, Development, Testing, Deployment).
   - Research:
   - Design:
   - Development:
   - Testing:
   - Deployment:""",
          """What are the estimated costs associated with each phase of development? Please provide a realistic breakdown of costs (e.g., Personnel, Tools, Licensing, etc.)
   - Research:
   - Design:
   - Development:
   - Testing:
   - Deployment:""",
          "What is the total budget allocated for the development of the MVP?",
          "What is the initial target user base for the MVP, and how do you plan to acquire these users?",
          "What is the initial target user base for the MVP, and how do you plan to acquire these users?",
          "What strategies will you use to scale the user base and the product (e.g., marketing campaigns, partnerships, feature enhancements)?",
          "How will you handle increased demand and ensure the product scales effectively?",
          " What are the projected costs involved in scaling operations (e.g., website, additional servers, marketing expenses, customer support)?",
          "What is the estimated cost for maintaining the MVP, including fixes, server costs, and minor feature upgrade?",
          "How much reserve budget do you have allocated for contingency planning?",
          "Processamento intermediario Operacional",
          "Pergunta Operacional gerada 1",
          "Pergunta Operacional gerada 2",
          "Pergunta Operacional gerada 3",
          "Pergunta Operacional gerada 4",
          "Pergunta Operacional gerada 5",
          "Pergunta Operacional gerada 6",
          "Pergunta Operacional gerada 7",
          "Pergunta Operacional gerada 8",
          "Pergunta Operacional gerada 9",
          "Pergunta Operacional gerada 10",
          "Processamento Operacional",
          "Criação do PDF Operacional",
          "Criação do Subgrafo Operacional",
          "Envio do arquivo Operacional",
           ]

def grafico(numero):
       if numero == 0:
              return ["What idea, product or service do you have in mind?",
                  "How many benefits of your idea can you list?",
                  "Why does your audience need this product?",
                  "How will people use this product or service?",
                  "How do you plan to monetize this MVP?",
                  "Why will the public choose your solution and not other competitors that are already on the market?",
                  "Who is your target audience?",
                  "Have you already carried out any market research to validate your demand?",
                  "What metrics do you have in mind to quantify the success of your MVP? (Number of customers, revenue, number of views, number of good reviews.....)",
                 "Processamento inicial inicial",
                 "Pergunta inicial gerada 1",
                 "Pergunta inicial gerada 2",
                 "Pergunta inicial gerada 3",
                 "Pergunta inicial gerada 4",
                 "Pergunta inicial gerada 5",
                 "Pergunta inicial gerada 6",
                 "Pergunta inicial gerada 7",
                 "Pergunta inicial gerada 8",
                 "Pergunta inicial gerada 9",
                 "Pergunta inicial gerada 10",
                 "Processamento inicial",
                 "Criação do PDF inicial",
                 "Criação do Subgrafo inicial",
                 "Envio do arquivo inicial",]
       elif numero == 1:
              return ["What is the problem you believe our MVP is solving?",
                 "Do you find the provided solution relevant and urgent for the defined problem? Why?",
                 "How do you think our solution addresses the problem identified?",
                 "How significant do you think this problem is in the current market?\n- Please rate the market need from 1 (low urgency) to 10 (high urgency).",
                 "What aspects of your solution do you find unique compared to existing market alternatives?",
                 "In your opinion, why is our solution superior to other available options in the market?",
                 "How does our MVP add value to customers?",
                 "Processamento Picth Aprofundadas",
                 "Pergunta Picth gerada 1",
                 "Pergunta Picth gerada 2",
                 "Pergunta Picth gerada 3",
                 "Pergunta Picth gerada 4",
                 "Pergunta Picth gerada 5",
                 "Pergunta Picth gerada 6",
                 "Pergunta Picth gerada 7",
                 "Pergunta Picth gerada 8",
                 "Pergunta Picth gerada 9",
                 "Pergunta Picth gerada 10",
                 "Processamento Picth",
                 "Criação do PDF Picth",
                 "Criação do Subgrafo Picth",
                 "Envio do arquivo Picth",]
       elif numero == 2:
              return [
                 "What are the general objectives of your marketing strategy for the MVP?",
                 "Can you list the specific KPIs (Key Performance Indicators) you plan to use to measure the success of our marketing strategy?",
                 "Can you describe the market segments we are targeting?",
                 "Are there plans to expand the target audience in the future? If so, how?",
                 "Have specific customer personas been developed? If so, please describe one of them.",
                 "What marketing channels do you recommend for our MVP and why? Options might include digital (email, PPC), social media (Facebook, Instagram, LinkedIn), traditional (TV, print, radio), etc.",
                 "How have you defined the visual identity and branding for the MVP?",
                 "How flexible is the implementation schedule to accommodate potential adjustments based on market response?",
                 "Processamento Marketing Aprofundadas",
                 "Pergunta Marketing gerada 1",
                 "Pergunta Marketing gerada 2",
                 "Pergunta Marketing gerada 3",
                 "Pergunta Marketing gerada 4",
                 "Pergunta Marketing gerada 5",
                 "Pergunta Marketing gerada 6",
                 "Pergunta Marketing gerada 7",
                 "Pergunta Marketing gerada 8",
                 "Pergunta Marketing gerada 9",
                 "Pergunta Marketing gerada 10",
                 "Processamento Marketing",
                 "Criação do PDF Marketing",
                 "Criação do Subgrafo Marketing",
                 "Envio do arquivo Marketing",
                 "Processamento Personas",
                 "Criação do PDF Personas",
                 "Criação do Subgrafo Personas",
                 "Envio do arquivo Personas",]
       elif numero == 3:
              return [
                 "Who would most benefit from this product or service?",
                  "Describe two other benefits that this MVP has that were not observed?",
                  "In your opinion, who would be the best target audience and why?"
                  "What is your recommendation for the value of this mvp for the end customer? Justify your answer.",
                  "What is the size of the market that will buy this product or service?"
                  "Who would be the competitors for this product or service?"
                  "Do you consider this product or service viable?",
                  "What are the most efficient channels to reach our target audience?",
                  "If you could improve this MVP proposal, what would you improve?",
                 "Processamento intermediario Aprofundadas",
                 "Pergunta Aprofundadas gerada 1",
                 "Pergunta Aprofundadas gerada 2",
                 "Pergunta Aprofundadas gerada 3",
                 "Pergunta Aprofundadas gerada 4",
                 "Pergunta Aprofundadas gerada 5",
                 "Pergunta Aprofundadas gerada 6",
                 "Pergunta Aprofundadas gerada 7",
                 "Pergunta Aprofundadas gerada 8",
                 "Pergunta Aprofundadas gerada 9",
                 "Pergunta Aprofundadas gerada 10",
                 "Processamento Aprofundadas",
                 "Criação do PDF Aprofundadas",
                 "Criação do Subgrafo Aprofundadas",
                 "Envio do arquivo Aprofundadas",]
       elif numero == 4:
              return [
                 """What are the primary functions and features that must be included in the MVP to deliver value to early customers?
              - Feature 1:
              - Feature 2:
              - Feature 3:""",
                 "Are there any specific design requirements or user interface elements that are essential for the MVP?",
                 """What is the projected timeline for each development phase of the MVP? Please provide a detailed breakdown of the timeline (e.g., Research, Design, Development, Testing, Deployment).
              - Research:
              - Design:
              - Development:
              - Testing:
              - Deployment:""",
                 """What are the estimated costs associated with each phase of development? Please provide a realistic breakdown of costs (e.g., Personnel, Tools, Licensing, etc.)
              - Research:
              - Design:
              - Development:
              - Testing:
              - Deployment:""",
                 "What is the total budget allocated for the development of the MVP?",
                 "What is the initial target user base for the MVP, and how do you plan to acquire these users?",
                 "What is the initial target user base for the MVP, and how do you plan to acquire these users?",
                 "What strategies will you use to scale the user base and the product (e.g., marketing campaigns, partnerships, feature enhancements)?",
                 "How will you handle increased demand and ensure the product scales effectively?",
                 " What are the projected costs involved in scaling operations (e.g., website, additional servers, marketing expenses, customer support)?",
                 "What is the estimated cost for maintaining the MVP, including fixes, server costs, and minor feature upgrade?",
                 "How much reserve budget do you have allocated for contingency planning?",
                 "Processamento intermediario Operacional",
                 "Pergunta Operacional gerada 1",
                 "Pergunta Operacional gerada 2",
                 "Pergunta Operacional gerada 3",
                 "Pergunta Operacional gerada 4",
                 "Pergunta Operacional gerada 5",
                 "Pergunta Operacional gerada 6",
                 "Pergunta Operacional gerada 7",
                 "Pergunta Operacional gerada 8",
                 "Pergunta Operacional gerada 9",
                 "Pergunta Operacional gerada 10",
                 "Processamento Operacional",
                 "Criação do PDF Operacional",
                 "Criação do Subgrafo Operacional",
                 "Envio do arquivo Operacional",
                  ]